home/urls.py
from django.urls import path,include
from . import views
app_name = "home"
urlpatterns = [
    path("",views.homepage,name="homepage"),
    path("thread/<int:id>", views.show_thread, name="show_thread"),
    path("get_threads", views.get_threads, name="get_threads"),
    path("create_thread", views.create_thread, name="create_thread"),
    path("get_threadform", views.get_threadform, name="get_threadform"),
    path("create_note/<int:thread_id>",views.create_note, name="create_note"),
    path("show_note/<int:id>", views.show_note,name="show_note"),
    path("delete_note/<int:note_id>", views.delete_note, name="delete_note"),
    path("show_thread_settings/<int:id>",views.show_thread_settings, name="show_thread_settings"),
    path("access/<int:id>", views.thread_access,name="access"),
    path("threadaccess/<int:id>",views.thread_accestype, name="threadaccess")
]

threadnote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser
#from ckeditor.fields import RichTextField
from tinymce.models import HTMLField
# Create your models here.

class User(AbstractUser):
    friends = models.ManyToManyField("self", through="Friendship")
    # unique=True the name should be unique
    def __str__(self):
        return self.username
    
    def get_friends(self):
        friendshiplist=Friendship.objects.filter(Q(friend_a=self)|Q(friend_b=self))
        friendslist = []
        for friendship in friendshiplist:
            friendslist.append(friendship.friend_a)
            friendslist.append(friendship.friend_b)
        return set(friendslist)

    def get_threads(self):
        # Get threads created by the user or threads where the user has access
        return Thread.objects.filter(Q(creator=self) | Q(users=self) | Q(privacy="p")).distinct().order_by("-modify_date")
    
class Friendship(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    friend_a = models.ForeignKey(User, related_name='friendship_set_a', on_delete=models.CASCADE, db_index=True)
    friend_b = models.ForeignKey(User, related_name='friendship_set_b', on_delete=models.CASCADE, db_index=True)
    class Meta:
        unique_together = ['friend_a', 'friend_b']
class Tnbase(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    pin = models.BooleanField(db_default=False)
    is_active = models.BooleanField(db_default=True)
    class Meta:
        abstract = True

class Thread(Tnbase):
    creator = models.ForeignKey("User", related_name="threads", on_delete=models.CASCADE)
    title = models.CharField(max_length = 30,blank=False)
    description = models.TextField(max_length = 256, blank=True)
    users = models.ManyToManyField('User', through = "Access")
    privacy_options = {
        "p": "Public",
        "a": "Access only",
    }
    privacy = models.CharField(max_length=1,choices=privacy_options, db_default="a")

    def __str__(self):
        return self.title
    
    def get_notes(self):
        return self.notes.all().order_by("-modify_date")

class Access(models.Model):
    thread = models.ForeignKey(Thread, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    access_type_options = {
        "v" : "Access View",
        "e" : "Access Edit"
    }
    access_type = models.CharField(max_length=1,choices=access_type_options, db_default="e")
    class Meta:
        unique_together = ['user', 'thread']

class Note(Tnbase):
    creator = models.ForeignKey("User", related_name="notes",on_delete=models.CASCADE)
    thread = models.ForeignKey("Thread", related_name="notes", on_delete=models.CASCADE)
    content = HTMLField(blank=True)
    #last_user = models.ForeignKey("User", on_delete=models.do_nothing)
    def __str__(self):
        return self.content[:20]

class Notification(models.Model):
    sender = models.ForeignKey(User, related_name='sent_notifications', on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name='received_notifications', on_delete=models.CASCADE)
    notification_type = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.username} to {self.recipient.username}: {self.message}"

home/forms.py
from django.forms import ModelForm
from django import forms
from .models import Thread, Note
from tinymce.widgets import TinyMCE

class Noteform(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    
    class Meta:
        model = Note
        fields = ["content"]
        widgets = {
            "content":TinyMCE()
        }
    

class Threadsetting(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    class Meta:
        model = Thread
        fields = ["title","description","privacy"]
        widgets = {
            'description': forms.Textarea(attrs={'class': 'textarea textarea-primary', 'placeholder': 'Your Description here'}),
            'title': forms.TextInput(attrs={'class': 'input input-bordered w-full max-w-xs p-5', 'placeholder': 'Your Thread Title'}),
            'privacy':forms.Select(attrs={'class': 'select select-primary w-full max-w-xs', 'placeholder': 'Your Thread Title'}),
        }
    


class Threadform(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label = ""
    class Meta:
        model = Thread
        fields = ["title","description"]
        # Override the widget for field1
        # labels = {
        #     'title': 'Tasdasdatle',
        #     #'users': 'Access',
        #  }

        widgets = {
            'description': forms.Textarea(attrs={'class': 'textarea textarea-primary', 'placeholder': 'Your Description here'}),
            'title': forms.TextInput(attrs={'class': 'input input-bordered w-full max-w-xs p-5', 'placeholder': 'Your Thread Title'}),
        }

    # def __init__(self, *args, **kwargs):
    #     creator = kwargs.pop('creator', None)
    #     friends = kwargs.pop('friends', [])

    #     super().__init__(*args, **kwargs)

    #     # Filter the users field choices to include only friends
    #     self.fields['users'].queryset = friends

    #     self.creator = creator

home/views.py
from django.shortcuts import render,HttpResponse,redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import Threadform, Noteform, Threadsetting
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Note, Thread, User, Access

def is_authorized(user_id, thread_id):
    user = get_object_or_404(User, id=user_id)
    thread = get_object_or_404(Thread, id=thread_id)
    access = Access.objects.filter(thread= thread, user=user).first()
    if user == thread.creator or access.access_type == "e":
        return True
    else:
        return False

# Create your views here.
@login_required
def homepage(request):
    threads = request.user.get_threads()
    paginator = Paginator(threads,9)
    if "page" in request.GET:
        pagenumber = int(request.GET["page"])
        page = paginator.get_page(pagenumber)
        content = {"user":request.user, "threadform":Threadform(), "page":page}
        return render(request,"home/threads.html",content)
    else:
        page = paginator.get_page(1)
    content = {"user":request.user, "threadform":Threadform(), "page":page}
    return render(request, "home/index.html",content)

@login_required
def show_thread(request, id):
    thread = get_object_or_404(Thread, id=id)
    content={"thread":thread, "user": request.user}
    return render(request, "home/thread.html", content)

@login_required
def get_threads(request):
    user = request.user
    threads = request.user.get_threads()
    paginator = Paginator(threads,9)
    if "page" in request.GET:
        pagenumber = int(request.GET["page"])
        page = paginator.get_page(pagenumber)
    else:
        page = paginator.get_page(1)
    content = {"user":user,"page":page}
    return render(request,"home/threads.html",content)

@login_required
def get_threadform(request):
    content = {"threadform":Threadform()}
    return render(request, "home/threadform.html", content)

@login_required
def create_thread(request):
    print("you are creating a thread")
    print(request.POST)
    user = request.user
    if request.method == "POST":
        form = Threadform(request.POST)
        if form.is_valid():
            # creating the form
            form.instance.creator = user
            form.save()
            return show_thread(request, form.instance.pk)
        return HttpResponse("404")
    return HttpResponse("404")


@login_required
def show_note(request,id):
    user = request.user
    note = get_object_or_404(Note, id=id)
    if request.method == "POST" and is_authorized(user.id, note.thread.id):
        print(request.POST)
        form = Noteform(request.POST,instance=note)
        #print(request.POST)
        if form.is_valid():
            form.save()
            print("Saved")
            return render(request, "home/toast.html", {"message":"Note Updated Successfully","alert":"success"})
        return HttpResponse("404")
    form = Noteform(instance = note)
    content = {"Noteform":form, "note":note, "user":user}
    return render(request, "home/note.html", content)
    #return HttpResponse("Not Authorized") 

@login_required
def create_note(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id)
    if is_authorized(request.user.id, thread.id):
        user = request.user
        note = Note()
        note.creator = user
        note.thread = thread
        note.save()
        request.method="None"
        return show_note(request,note.pk)
    return HttpResponse("404")
    

@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    notethread = note.thread
    if request.method == "DELETE" and is_authorized(request.user.id, notethread.id):
        note.delete()
        return show_thread(request, notethread.pk)
    return HttpResponse("404")

@login_required
def thread_access(request, id):
    thread = get_object_or_404(Thread, id=id)
    content={"thread":thread}
    return render(request,'home/access.html',content)

@login_required
def thread_accestype(request, id):
    user = request.user
    thread = get_object_or_404(Thread, id=id)
    if thread.creator == user:
        # we do our access stuff here
        if request.method == "POST":
            content = request.POST
            if "username" in content.keys():
                username = content["username"]
                access_type = content["accesstype"]
                access_user = User.objects.filter(username=username).first()
                print(thread.creator.get_friends())
                print(access_user in thread.creator.get_friends())
                if access_user!=None and access_user!= thread.creator and (access_user not in thread.users.all()) and (access_user in thread.creator.get_friends()):
                    access = Access(thread=thread, user=access_user, access_type=access_type)
                    access.save()
                    #return render(request, "home/toast.html", {"message":"User Added Successfully","alert":"success"})
                    return render(request, "home/access_item.html",{"aces":access,"message":"User Added Successfully","alert":"success"})
                return render(request, "home/toast.html", {"message":"Wrong User Name or User is not your friend","alert":"error"})
            return HttpResponse("404")
        if request.method == "DELETE":
            access_id = request.GET.get("access_id")
            access_id = int(access_id)
            access = get_object_or_404(Access, id=access_id)
            if access.thread == thread:
               access.delete()
            return render(request, "home/toast.html", {"message":"User Deleted Successfully","alert":"success"})
        return HttpResponse("404")
    return HttpResponse("404")

@login_required
def show_thread_settings(request,id):
    thread = get_object_or_404(Thread, id=id)
    if request.method == "POST" and is_authorized(request.user.id, thread.id):
        # here we update the Settings
        settingsform = Threadsetting(request.POST,instance=thread)
        if settingsform.is_valid():
            settingsform.save()
            return render(request, "home/toast.html", {"message":"Settings Updated Successfully","alert":"success"})

    if request.method == "DELETE"and is_authorized(request.user.id, thread.id):
        thread.delete()
        return get_threads(request)
    settingsform = Threadsetting(instance = thread)
    content = {"thread":thread, "settingsform":settingsform}
    return render(request, "home/thread_settings.html", content)

home/templates/home/access.html
<div class="showerleft">
    <button
      class="btn btn-circle"
      hx-get="{% url 'home:show_thread' thread.pk %}"
      hx-target="#base"
      hx-swap="innerHtml"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M6 18L18 6M6 6l12 12"
        />
      </svg>
    </button>
    {% load mytags %}
    <div class="btn btn-ghost btn-lg">{{thread}}</div>
    
    <h4 class = "p-4">this thread Access Settings</h4>

    <div id="here">
        <select name="accesstype" class="select select-primary w-full max-w-xs" required>
            <option value="v" selected>Access View</option>
            <option value="e">Access Edit</option>
          </select>
        <input id="username" class="input input-bordered w-full max-w-xs p-5" placeholder="Friend name" name="username" type="text"/>
        <button class="btn btn-primary" hx-post="{% url 'home:threadaccess' thread.pk %}" hx-target="#res" hx-swap="afterbegin" hx-include="[name='username'],[name='accesstype']">Add</button>
    </div>
    <br>
    <br>
    
    <div id="res" class="grid sm:grid-cols1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {% for aces in thread.access_set.all %}
      <div id='accesshome{{aces.pk}}' class="collapse bg-base-200">
        <input type="checkbox"/> 
        <div class="collapse-title text-xl font-medium">
          {{aces.user}} <p>{{ aces.access_type|accesstype}}</p>
        </div>
        <div class="collapse-content">
          <button class="btn btn-circle btn-warning" hx-delete="{% url 'home:threadaccess' thread.pk %}?access_id={{aces.pk}}" hx-target="#toasting" hx-swap="beforeend" _="on click wait 1s then remove #accesshome{{aces.pk}}">remove</button>
        </div>
      </div>
      {% endfor %}
    </div>
    <br>
    <br>
    <!-- Open the modal using ID.showModal() method -->
    
  <script>
    // console.log("your script is working")
    // document.getElementById("here").addEventListener("htmx:aftersend", ({ detail }) => {
    //     // log the request object to the console
    //     console.log(detail);
    //     // append "hi" to the form data
    //     //detail.parameters["greeting"] = "hi";
    //     // reset the form
    //     //document.getElementById("user-input").reset();
    //   });
  </script>      
  </div>
  

home/templates/home/access_item.html
{% load mytags %}
<div id='accesshome{{aces.pk}}' class="collapse bg-base-200">
    <input type="checkbox"/> 
    <div class="collapse-title text-xl font-medium">
      {{aces.user}} <p>{{ aces.access_type|accesstype}}</p>
    </div>
    <div class="collapse-content">
        <button class="btn btn-circle btn-warning" hx-delete="{% url 'home:threadaccess' aces.thread.pk %}?access_id={{aces.pk}}" hx-target="#toasting" hx-swap="beforeend" _="on click wait 1s then remove #accesshome{{aces.pk}}">remove</button>
    </div>
</div>
<div hx-swap-oob="beforeend:#toasting">
<div id="toas" class="alert alert-{{alert}} self-removing-div" _="on mouseover remove me">
    <span>{{message}}</span>
</div>
<script>    
    setTimeout(function(){
        var popup = document.getElementById("toas")
        popup.remove();
    }, 4000);
</script>
</div>

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    {% load static %}
    {% load mytags %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="{% static 'htmx.min.js' %}"></script>
    <script src="{% static '_hyperscript.min.js' %}"></script>
    <title>Document</title>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <!-- Nav Bar-->
    <div class="navbar bg-base-100">
      <div class="navbar-start">
        <div class="dropdown">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16M4 18h7"
              />
            </svg>
          </div>
          <ul
            tabindex="0"
            class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
          >
            <li><a href="{% url 'home:homepage' %}">Homepage</a></li>
            <li><a>My Settings</a></li>
            <li><a href="{% url 'account_logout' %}">logout</a></li>
          </ul>
        </div>
      </div>
      <div class="navbar-center">
        <a class="btn btn-ghost text-xl">{{user.username}}</a>
      </div>
      <div class="navbar-end">
        <button class="btn btn-ghost btn-circle">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
            />
          </svg>
        </button>
        <button class="btn btn-ghost btn-circle">
          <div class="indicator">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
              />
            </svg>
            <span
              id="notfnum"
              class="badge badge-xs badge-primary indicator-item hidden"
            ></span>
          </div>
        </button>
        <button class="btn btn-ghost btn-circle">
          <label class="swap swap-rotate">
            <!-- this hidden checkbox controls the state -->
            <input type="checkbox" class="theme-controller" value="synthwave" />

            <!-- sun icon -->
            <svg
              class="swap-on fill-current w-7 h-7"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
            >
              <path
                d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z"
              />
            </svg>

            <!-- moon icon -->
            <svg
              class="swap-off fill-current w-7 h-7"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
            >
              <path
                d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z"
              />
            </svg>
          </label>
        </button>
      </div>
    </div>
    <!-- Nav Bar End -->
    <div class="flex justify-center">Home Page</div>
    <div class="pr-10 pl-10">
      <div role="tablist" class="tabs tabs-boxed">
        <a
          hx-get="{% url 'home:get_threads' %}"
          hx-target="#base"
          hx-swap="innerHtml"
          role="tab"
          class="tab tabi tab-active"
          _="on click remove .tab-active from .tabi then add .tab-active to me"
          >Threads</a
        >
        <a
          hx-get="{% url 'home:get_threadform' %}"
          hx-target="#base"
          hx-swap="innerHtml"
          role="tab"
          class="tab tabi"
          _="on click remove .tab-active from .tabi then add .tab-active to me"
          >Create Thread</a
        >
      </div>
    </div>
    <div id="base" class="pt-8 pr-12 pl-12 transition-all">
      {% block threadblock %} {% endblock %}
    </div>
    <!-- <span hx-indicator="loaderi" class="loading loading-dots loading-lg"></span> -->
    <div id="toasting" class="toast toast-end"></div>
    <script>
    </script>
  </body>
  <br><br><br><br><br><br><br><br><br>
  <footer class="footer footer-center p-10 bg-primary text-primary-content">
    <aside>
      <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="inline-block fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
      <p class="font-bold">
        JoeDanial <br>
      </p> 
      <p>Copyright © 2024 - All right reserved</p>
    </aside>
    <nav>
      <div class="grid grid-flow-col gap-4">
        <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg></a>
        <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
        <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
      </div>
    </nav>
    <link href="{% static 'full.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <script src="{% static '3.4.1' %}"></script>
    <link href="{% static 'my.css'%}" rel="stylesheet" type="text/css" />
  </footer>
</html>

home/templates/home/thread.html
<div class="showerleft">
  {% load mytags %}
  {% is_authorized_edit user.id thread.id as authorized %}

  <div class="btn btn-ghost btn-lg" hx-get="{% url 'home:show_thread' thread.pk %}" hx-target="#base"
    hx-swap="innerHtml">{{thread}}</div>
  <p class="pb-4 pl-4">{{thread.description}}</p>
  {% if authorized %}
  <div class="flex">
    <button class="btn btn-sm" hx-get="{% url 'home:show_thread_settings' thread.pk %}" hx-target="#base"
      hx-swap="innerHtml">Settings</button>
    <button class="btn btn-sm" hx-get="{% url 'home:access' thread.pk %}" hx-target="#base"
      hx-swap="innerHtml">Access</button>
    <button hx-post="{% url 'home:create_note' thread.pk %}" hx-target="#base" hx-swap="innerHtml"
      class="btn btn-sm btn-primary">
      Create Note
    </button>
  </div>
  {% endif %}
  <br>
  <br>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-5">
    {% for note in thread.get_notes %}
    <div class="card shadow-xl transform transition-all hover:scale-125">
      <div class="card-body">
        <h2 class="card-title">{{note | safe}}</h2>
        <p>{{note.creator}}</p>
        <div class="card-actions justify-end">
          <button hx-get="{% url 'home:show_note' note.pk %}" hx-target="#base" hx-swap="innerHtml"
            class="btn btn-primary">
            Open Note
          </button>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
</div>

home/templates/home/toast.html
<div id="toas" class="alert alert-{{alert}} self-removing-div" _="on mouseover remove me">
    <span>{{message}}</span>
</div>
<script>    
    setTimeout(function(){
        var popup = document.getElementById("toas")
        popup.remove();
    }, 4000);
</script>